name: Nx CI
on: [pull_request]

jobs:
  pr:
    name: Nx Cloud Checker
    uses: nrwl/ci/.github/workflows/nx-cloud-main.yml@v0.13.1
    with:
      number-of-agents: 3
      main-branch-name: master
      init-commands: |
        yarn nx-cloud start-ci-run --stop-agents-after="build"
      parallel-commands: |
        yarn nx-cloud record -- yarn nx format:check
      parallel-commands-on-agents: |
        yarn nx affected -t lint,test,build --parallel=3

  agents:
    name: Nx Cloud - Agents
    uses: nrwl/ci/.github/workflows/nx-cloud-agents.yml@v0.13.1
    with:
      number-of-agents: 3
